In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("Heart.csv")


df.head()

print("Dataset Shape:", df.shape)

df.info()


print("\nNumber of null values in each column:")
print(df.isnull().sum())

Dataset Shape: (303, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  303 non-null    int64
 1   Age         303 non-null    int64
 2   Sex         303 non-null    int64
 3   ChestPain   303 non-null    object
 4   RestBP      303 non-null    int64
 5   Chol        303 non-null    int64
 6   Fbs         303 non-null    int64
 7   RestECG     303 non-null    int64
 8   MaxHR       303 non-null    int64
 9   ExAng       303 non-null    int64
 10  Oldpeak     303 non-null    float64
 11  Slope       303 non-null    int64
 12  Ca          299 non-null    float64
 13  Thal        301 non-null    object
 14  AHD         303 non-null    object
dtypes: float64(2), int64(10), object(3)
memory usage: 35.6+ KB

Number of null values in each column:
Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [ ]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [ ]:
central_tendency = pd.DataFrame({
    "Mean": df.mean(numeric_only=True),
    "Median": df.median(numeric_only=True),
    "Mode": df.mode(numeric_only=True).iloc[0]
})

central_tendency

               Mean  Median   Mode
Age       54.438944    56.0   58.0
Sex        0.679868     1.0    1.0
RestBP   131.689769   130.0  120.0
Chol     246.693069   241.0  197.0
Fbs        0.148515     0.0    0.0
RestECG    0.990099     1.0    0.0
MaxHR    149.607261   153.0  162.0
ExAng      0.326733     0.0    0.0
Oldpeak    1.039604     0.8    0.0
Slope      1.600660     2.0    1.0
Ca         0.672241     0.0    0.0

In [ ]:
df["Ca"].fillna(df["Ca"].median(), inplace=True)
df["Thal"].fillna(df["Thal"].mode()[0], inplace=True)

/tmp/ipython-input-2228993098.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Ca"].fillna(df["Ca"].median(), inplace=True)
/tmp/ipython-input-2228993098.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Thal"].fillna(df["Thal"].mode()[0], inplace=True)

In [ ]:
categorical_cols = ["ChestPain", "Thal"]
numerical_cols = [
    "Age", "Sex", "RestBP", "Chol", "Fbs",
    "RestECG", "MaxHR", "ExAng",
    "Oldpeak", "Slope", "Ca"
]

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in categorical_cols:
    df[col] = encoder.fit_transform(df[col])

In [ ]:
df["AHD"] = df["AHD"].map({"No": 0, "Yes": 1})

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        303 non-null    float64
 1   Sex        303 non-null    float64
 2   ChestPain  303 non-null    int64
 3   RestBP     303 non-null    float64
 4   Chol       303 non-null    float64
 5   Fbs        303 non-null    float64
 6   RestECG    303 non-null    float64
 7   MaxHR      303 non-null    float64
 8   ExAng      303 non-null    float64
 9   Oldpeak    303 non-null    float64
 10  Slope      303 non-null    float64
 11  Ca         303 non-null    float64
 12  Thal       303 non-null    int64
 13  AHD        303 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 33.3 KB

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,0.948726,0.686202,3,0.757525,-0.264900,2.394438,1.016684,0.017197,-0.696631,1.087338,2.274579,-0.711131,0,0
1,1.392002,0.686202,0,1.611220,0.760415,-0.417635,1.016684,-1.821905,1.435481,0.397182,0.649113,2.504881,1,1
2,1.392002,0.686202,0,-0.665300,-0.342283,-0.417635,1.016684,-0.902354,1.435481,1.346147,0.649113,1.432877,2,1
3,-1.932564,0.686202,1,-0.096170,0.063974,-0.417635,-0.996749,1.637359,-0.696631,2.122573,2.274579,-0.711131,1,0
4,-1.489288,-1.457296,2,-0.096170,-0.825922,-0.417635,1.016684,0.980537,-0.696631,0.310912,-0.976352,-0.711131,1,0

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop("AHD", axis=1)
y = df["AHD"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred_lr = lin_reg.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

r2_lr = r2_score(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))

print("Linear Regression Performance")
print("R² Score:", r2_lr)
print("RMSE:", rmse_lr)

Linear Regression Performance
R² Score: 0.5309770235665081
RMSE: 0.34201189613073746

In [ ]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred_prob = log_reg.predict_proba(X_test)[:, 1]

In [ ]:
r2_log = r2_score(y_test, y_pred_prob)
rmse_log = np.sqrt(mean_squared_error(y_test, y_pred_prob))

print("Logistic Regression Performance")
print("R² Score:", r2_log)
print("RMSE:", rmse_log)

Logistic Regression Performance
R² Score: 0.5496096301708346
RMSE: 0.33514959665336946

In [ ]:
from sklearn.linear_model import LinearRegression, LogisticRegression

lin_reg = LinearRegression()
log_reg = LogisticRegression(max_iter=1000)

lin_reg.fit(X_train, y_train)
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred_lr = lin_reg.predict(X_test)

y_pred_log = log_reg.predict_proba(X_test)[:, 1]

In [ ]:
y_pred_ensemble = (y_pred_lr + y_pred_log) / 2

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

r2_ensemble = r2_score(y_test, y_pred_ensemble)
rmse_ensemble = np.sqrt(mean_squared_error(y_test, y_pred_ensemble))

print("Ensemble Model Performance")
print("R² Score:", r2_ensemble)
print("RMSE:", rmse_ensemble)

Ensemble Model Performance
R² Score: 0.5506010542116531
RMSE: 0.3347805185747759

In [ ]:
print("Model Comparison\n")

print("Linear Regression")
print("R²:", r2_score(y_test, y_pred_lr))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lr)))

print("\nLogistic Regression")
print("R²:", r2_score(y_test, y_pred_log))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_log)))

print("\nEnsemble Model")
print("R²:", r2_ensemble)
print("RMSE:", rmse_ensemble)

Model Comparison

Linear Regression
R²: 0.5309770235665081
RMSE: 0.34201189613073746

Logistic Regression
R²: 0.5496096301708346
RMSE: 0.33514959665336946

Ensemble Model
R²: 0.5506010542116531
RMSE: 0.3347805185747759